"""add ts_raw, attrs, parse_kind, parse_confidence to boost log event records

Revision ID: 3188860a88fa
Revises: 577d9ec187c0
Create Date: 2026-02-05 20:54:39.127902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3188860a88fa'
down_revision: Union[str, Sequence[str], None] = '577d9ec187c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_events', sa.Column('ts_raw', sa.String(), nullable=True))
    op.add_column('log_events', sa.Column('attrs', sa.JSON(), nullable=True))
    op.add_column('log_events', sa.Column('parse_kind', sa.String(), nullable=True))
    op.add_column('log_events', sa.Column('parse_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_events', 'parse_confidence')
    op.drop_column('log_events', 'parse_kind')
    op.drop_column('log_events', 'attrs')
    op.drop_column('log_events', 'ts_raw')
    # ### end Alembic commands ###
