"""add seq column for log_event and improve indexing

Revision ID: 577d9ec187c0
Revises: c5d40fad8e04
Create Date: 2026-02-05 18:06:52.351716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577d9ec187c0'
down_revision: Union[str, Sequence[str], None] = 'c5d40fad8e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_events', sa.Column('seq', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_log_events_ts'), table_name='log_events')
    op.create_index('ix_log_events_ingestion_id_fingerprint', 'log_events', ['ingestion_id', 'fingerprint'], unique=False)
    op.create_index('ix_log_events_ingestion_id_seq', 'log_events', ['ingestion_id', 'seq'], unique=False)
    op.create_index('ix_log_events_ingestion_id_ts', 'log_events', ['ingestion_id', 'ts'], unique=False)
    op.create_unique_constraint('uq_log_events_ingestion_id_seq', 'log_events', ['ingestion_id', 'seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_log_events_ingestion_id_seq', 'log_events', type_='unique')
    op.drop_index('ix_log_events_ingestion_id_ts', table_name='log_events')
    op.drop_index('ix_log_events_ingestion_id_seq', table_name='log_events')
    op.drop_index('ix_log_events_ingestion_id_fingerprint', table_name='log_events')
    op.create_index(op.f('ix_log_events_ts'), 'log_events', ['ts'], unique=False)
    op.drop_column('log_events', 'seq')
    # ### end Alembic commands ###
