"""cascade on deletion

Revision ID: 5e70ba0df0d8
Revises: f3fcaeb25535
Create Date: 2026-01-27 15:41:06.474169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e70ba0df0d8'
down_revision: Union[str, Sequence[str], None] = 'f3fcaeb25535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_analyses_ingestion_id_fkey'), 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analyses', 'ingestions', ['ingestion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('findings_ingestion_id_fkey'), 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'ingestions', ['ingestion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('org_members_org_id_fkey'), 'org_members', type_='foreignkey')
    op.drop_constraint(op.f('org_members_user_id_fkey'), 'org_members', type_='foreignkey')
    op.create_foreign_key(None, 'org_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'org_members', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_org_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_org_id_fkey'), 'projects', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'org_members', type_='foreignkey')
    op.drop_constraint(None, 'org_members', type_='foreignkey')
    op.create_foreign_key(op.f('org_members_user_id_fkey'), 'org_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('org_members_org_id_fkey'), 'org_members', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(op.f('findings_ingestion_id_fkey'), 'findings', 'ingestions', ['ingestion_id'], ['id'])
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analyses_ingestion_id_fkey'), 'ai_analyses', 'ingestions', ['ingestion_id'], ['id'])
    # ### end Alembic commands ###
