"""add finding_status to ingestion table

Revision ID: 7fe1052fa729
Revises: b16eaecb1e1a
Create Date: 2026-02-07 12:44:47.381930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe1052fa729'
down_revision: Union[str, Sequence[str], None] = 'b16eaecb1e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestions', sa.Column('finding_status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestions', 'finding_status')
    # ### end Alembic commands ###
