"""add scope_type, scope_id for ai analyses and remove mode

Revision ID: a766af5aa747
Revises: 7fe1052fa729
Create Date: 2026-02-10 18:47:32.671153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a766af5aa747'
down_revision: Union[str, Sequence[str], None] = '7fe1052fa729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('scope_type', sa.String(), nullable=False))
    op.add_column('ai_analyses', sa.Column('scope_id', sa.String(), nullable=False))
    op.drop_column('ai_analyses', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ai_analyses', 'scope_id')
    op.drop_column('ai_analyses', 'scope_type')
    # ### end Alembic commands ###
