"""add matched_fingerprints and total_occurnces to findings table

Revision ID: b16eaecb1e1a
Revises: 3188860a88fa
Create Date: 2026-02-07 12:39:15.117177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b16eaecb1e1a'
down_revision: Union[str, Sequence[str], None] = '3188860a88fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('matched_fingerprints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('findings', sa.Column('total_occurrences', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'total_occurrences')
    op.drop_column('findings', 'matched_fingerprints')
    # ### end Alembic commands ###
