"""add name for users

Revision ID: c5d40fad8e04
Revises: 5e70ba0df0d8
Create Date: 2026-01-30 16:06:13.815991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d40fad8e04'
down_revision: Union[str, Sequence[str], None] = '5e70ba0df0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_log_events_ts'), 'log_events', ['ts'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_log_events_ts'), table_name='log_events')
    # ### end Alembic commands ###
