"""make analysis per scope unique per ingestion

Revision ID: fe22b6188068
Revises: c8c8644fed93
Create Date: 2026-02-10 19:06:20.478699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe22b6188068'
down_revision: Union[str, Sequence[str], None] = 'c8c8644fed93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ingestion_scope', 'ai_analyses', ['ingestion_id', 'scope_type', 'scope_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ingestion_scope', 'ai_analyses', type_='unique')
    # ### end Alembic commands ###
